### ISSUE TITLE
plot all years for each insecticide

### ISSUE THREAD

**Issue by goldingn** [idem-lab/map-ir-pipeline#79]
and add the names of the insecticides to the plots

**Comment by njtierney** [comment]
OK so instead of 
![image](https://github.com/user-attachments/assets/a5ee2773-d749-49a4-98de-7d7e140164a1)


We should have a remapping of "insecticide_1" to which insecticide that is.

**Comment by njtierney** [comment]
- [ ] Add year information in `create_pixel_map_data()`
- [ ] Add insecticide information in `create_pixel_map_data()`

**Comment by njtierney** [comment]
in #81 I update the maps to look like so

![image](https://github.com/user-attachments/assets/801cc4f7-cb70-4076-9f9d-1925e6c5e415)

The legend is a bit weird here, I'll see if that's something on my end

**Comment by goldingn** [comment]
Nice! But we need to work out why there is a 'none' insecticide class here. That 'none' class should only be used to denote genotypic data, and shouldn't have made its way through to these predictions. From memory, there were 4 insecticides in this run, in addition to the non class. Is it possible the labels got switched around?

**Comment by njtierney** [comment]
Yup got it, there are 4 insecticides:

```r
> unique(moyes_pheno_prepared$insecticide)
[1] "organochlorine"  "pyrethroid"      "carbamate"       "organophosphate"
> unique(moyes_geno_prepared$insecticide)
[1] "none"
```

So I'll have a dig in the pipeline to work out where these might be getting dropped

**Comment by njtierney** [comment]
OK so I had been a bit too clever when writing my little lookup - here is the table of the mappings of insecticide ID to the insecticide name

```
# A tibble: 5 × 2
  insecticide     insecticide_id
  <chr>                    <int>
1 pyrethroid                   5
2 organochlorine               3
3 carbamate                    1
4 organophosphate              4
5 none                         2
```

The idea was to create an index so you could do:

```r
insecticide_id_lookup[c(1:5)]
```

And it would return the corresponding insecticide that matched the mapping.

But because I forgot to sort it, we got whatever the character vector order was here above in that table.

We can see this in the original insecticide plot - there are 4, and we don't have number 2, which is "none".

So the good news is that we haven't accidentally dropped an insecticide in the model or swapped something out, and we can explain the above results.

**Comment by njtierney** [comment]
Here we go! I added the original IDs alongside the names just to make it super duper clear, we can remove those if we like :)

![image](https://github.com/user-attachments/assets/9aaa8844-9d5b-4b06-bcf7-5903ffbf5e02)

**Comment by goldingn** [comment]
Nice! Could you please make it (e.g.) "carbamate**s**_2015", "organochlorine**s**_2015"

**Comment by njtierney** [comment]
Investigate getting predictions out for all years

**Comment by njtierney** [comment]
done in #95
